name: Update GitHub Activity

on:
  schedule:
    - cron: '0 */6 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity:
    name: Update Recent GitHub Activity
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update GitHub Activity
        uses: TheDudeThatCode/recent-activity@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Updated recent GitHub activity'
          MAX_LINES: 10
        continue-on-error: true 
